### ISSUE TITLE
UX/design debt 2

### ISSUE THREAD

**Issue by jorisleker** [kiesraad/abacus#101]
- [x] On /input the link 'Bekijk de lijst met alle stembureaus' should have cursor:pointer (applies to all links)
- [x] The 'Shift + Enter' text should not break over multiple lines. Use `white-space: nowrap;`. Add some padding/margin below the 'Beginnen' button so the 'shift + enter' text is positioned neatly below the button (screenshot of how it should look: .5rem between button and text, text has .5rem margin-left (iso 2rem) <img width="273" alt="Scherm­afbeelding 2024-06-26 om 08 27 17" src="https://github.com/kiesraad/urn-uitslag/assets/3286523/358dac49-f065-4be1-ac9e-98ae2637f980">
- [x] There should be a spacer before the input for the list-totals, that's lacking. Also, there should **not** be a bottom border nor a background on the totals row. (see design below) <img width="683" alt="Scherm­afbeelding 2024-07-16 om 14 37 10" src="https://github.com/user-attachments/assets/efaf3af1-e574-40f4-9599-64163d360aeb">
- [x] ~On /input it looks like the width of the paragraph of text "Klopt de naam van het stembureau met de naam op je papieren proces verbaal? Dan kan je beginnen." is defined as a percentage of the parent column. Please use max-width instead, to  allow the text to occupy more space on smaller viewports. (applies to all paragraph texts: use max-width instead of percentage) <img width="573" alt="Scherm­afbeelding 2024-06-26 om 08 21 10" src="https://github.com/kiesraad/urn-uitslag/assets/3286523/2d23c334-c84f-455b-9332-5f261b05cd42">~
- [x] All pages have 'Abacus' as page title. Pages should have descriptive titles
  - /user/login --> Inloggen - Abacus
  - /user/account/setup --> Account instellen  - Abacus
  - /overview --> Overzicht verkiezingen - Abacus
  - /input --> Kies een stembureau - Abacus
  - /input/030 --> Invoeren `<stembureau nummer>` `<stembureau naam>`  - Abacus
- [x] When navigating to another page, user should be scrolled to top of page (repro: make your window less high, open list of polling stations on '/input', scroll to bottom of page and pick the last polling station. You will end up on a scrolled down version of the data entry screen (tested on https://6b2ce232.urn-uitslag.pages.dev/input/030 with long list of political groups)
- [x] Toggle between /input/030/numbers and /input/030/recount: the navigation items below "Is er herteld?" move up and down by 1 or 2 pixels. (more or less the same seems to happen if you click from an item halfway down the list to the bottom item and back. All items between the item halfway and the bottom most move a couple of pixels)
  - Looked into this a bit more: looks like the selected menu item just has 1px more padding (top and bottom / or a border maybe) then the non selected items. This make everything shift a bit, which stands out more if the items you toggle between are not adjacent to each other
- [x] The clickable area for items in the navigation menu in /input/030/ consists of just the text of the link. Ideally the clickable target is a big as the box we highlight for selected menu-items
- [x] The selected menu-item is a link. This should not be the case, do not link to the current page.
- [x] In the nav-menu and in the h2, the name of the political group should be prepended with `Lijst <lijstnummer> - ` 
- [ ] There is no fallback for the Geist Mono font in the input screen. When loading this page for the first time, the user might run into a situation where the input fields are rendered with Times New Roman as font. Possible solutions: → #267
  - Define a DMSans as fallback for the GeistMono font for the `--font-number` var
  - Only render the page if all resources have been loaded
- [x] The tooltip on paste only works on `/input/:pollingstation-id/numbers`, and not `/input/:pollingstation-id/list/:listnumber`. It should be implementend on all numeric inputs
- [x] when a list has exactly n\*25 candidates, the spacer/separator for the next 25 candidates is shown. The separator should only be added if there is a (n\*25)+1'nd  candidate.  ![Scherm­afbeelding 2024-08-01 om 11 13 17](https://github.com/user-attachments/assets/3f53492a-67ba-4b51-9b33-b3c92a219699)
- [x] The zebra-striping of the rows does not match the striping used in the paper forms. On paper, the first row of each 25 rows is white. In our digital form, row 26 and row 76 have a dark background. Each block of 25 rows should start with a white background.
![Scherm­afbeelding 2024-08-05 om 09 49 33](https://github.com/user-attachments/assets/9bf0d1d3-137e-41a8-be00-45be93a54869)
- [x] styling of the "Invoer afbreken" button isn't as designed (should not have an icon, padding / line-height looks off) → Fixed in #256 
- [x] Add hover state in navigation menu on ` /1/input/33/...` (see [Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=123-2660&t=3sUgnTRRixRyz5ld-11))
- [x] Check colors of icons (current page, empty input) in the nav menu. Have been updated in Figma, they were a subtly different color then the texts, is now consistent with text
- [x] font-weights: het is ok om de 500 en 600 te vervangen door 700 (gebeurt op een aantal buttons al, daar wordt een bold over de 500 weight gezet, waardoor die 500 al niks meer doet). Nb: alleen voor de DM Sans teksten. De 500 op Space Grotesk (de badges) moet zo blijven
- [ ] Fix layout issues on "Alle stembureaus zijn twee keer ingevoerd" (margin above button) and make not closable → #267
- [ ] Only show "account is ingesteld" when account has just been set up → #267

**Comment by Lionqueen94** [comment]
For setting the page titles, do we want to use a dependency for this or do it in a `useEffect`:
https://stackoverflow.com/questions/46160461/how-do-you-set-the-document-title-in-react
@praseodym @lkleuver

**Comment by praseodym** [comment]
> For setting the page titles, do we want to use a dependency for this or do it in a `useEffect`: https://stackoverflow.com/questions/46160461/how-do-you-set-the-document-title-in-react @praseodym @lkleuver

`useEffect` seems like the way to go, here's an example with `react-router-dom`: https://dev.to/rohitnirban/adding-page-titles-to-react-app-23oe
