### ISSUE TITLE
Backend: add 'recounted', 'differences' fields to API, including validation

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#110]
See epic (#97) for more details.

### TODO:
- [x] Implement validation rules in backend and texts in frontend: https://github.com/kiesraad/abacus-internal/blob/main/use-cases/GSB-validatieregels-plausibiliteitschecks.md#regels-voor-verschillen
- [x] Validate that field D should be equal to field H, unless the differences are explained in the relevant fields.
- [x] Add mock-api validation
