### ISSUE TITLE
Bug: Navigate should use pollingStationId instead of pollingStationNumber

### ISSUE THREAD

**Issue by Lionqueen94** [kiesraad/abacus#181]
### TODO: ###
- [x] Update list pollingstations route in backend as discussed
- [x] Fix navigate from polling station select page to input page
- [x] Fix implementation and add tests for F.01 on candidateVotesForm and VotersAndVotesForm
- [x] Update overrideOnce responses with changed DataEntryResponse
