### ISSUE TITLE
Inconsistent link colors and override of visited link color in feedback and alert components

### ISSUE THREAD

**Issue by jorisleker** [kiesraad/abacus#285]
We've reviewed the colors of our link styles to make them pass accessibility requirements.

The colors should be updated as follows:
- [x] link default: #155EEF 
- [x] link hover: #004EEB
- [x] link active: #0040C1
- [x] link visited: #6927DA

Also see [definition in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=3087-58933&node-type=FRAME&m=dev)

The colors apply for all links in texts (not in buttons).

There is one exception. In [feedback](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=136-2286&node-type=FRAME&m=dev) and [alert](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=985-19666&node-type=FRAME&m=dev) components (red/yellow/green or blue background) the _visited_ state of links should use the same color as the default state. Hover and active colors should override the visited color.

Acceptance criteria:
- [x] color of links adhere to scheme defined in this ticket
- [x] style of visited links in `feedback` and `alert` elements is same as non visited links
- [x] hover and active states always override visited state
- [x] style of visited links on `Controleren en opslaan` page is same as non visited links

Example of link in feedback component [in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=3085-18418&node-type=FRAME&t=yrnZQIcxc8CMyLZF-11)

**Comment by jorisleker** [comment]
Link colors are updated in https://github.com/kiesraad/abacus/pull/303
