### ISSUE TITLE
Epic: data entry screen - counts of voters and votes

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#3]
Bouwen van het invoerscherm "Aantal kiezers en stemmen" in de frontend en opslag in de backend. 
Design: https://www.figma.com/file/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---URN?type=design&node-id=126-2992&mode=design&t=IZ4M1Zw53dMBOCm2-11

Dit scherm komt overeen met de secties "3. Aantal toegelaten kiezers" en "4. Aantal uitgebrachte stemmen" van "Model 10-1: Proces-verbaal van een stembureau". Scope is alleen decentrale stemopneming (DSO) voor het gemeentelijk stembureau (GSB).

De keuze voor verkiezing en stembureau wordt gedaan door mocks/fixtures. Validatie van de invoer is geen onderdeel van deze epic. Opslag in de backend wel.

Taken in deze epic:

- [x] kiesraad/opstartfase-team-URN#111
- [x] kiesraad/urn-uitslag#2
- [x] kiesraad/urn-uitslag#4
- [x] kiesraad/urn-uitslag#5
- [x] kiesraad/urn-uitslag#6
- [x] #17
- [x] kiesraad/urn-uitslag#7
- [x] #18
- [x] #47
