### ISSUE TITLE
Epic: internationalization (i18n)

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#45]
Setup of internationalization in the frontend, e.g. using [i18next](https://www.i18next.com) / [react-i18next](https://www.npmjs.com/package/react-i18next) / [formatjs](https://formatjs.io/).

- [x] kiesraad/abacus-internal#120
- [x] kiesraad/abacus-internal#237
- [x] #409
- [x] Set up i18n library in frontend
- [x] #520

Other considerations: 
- which translation tool to use (@marjoleintamis has experience with this)
- test layout using all languages
- explicitly do not support right-to-left languages

**Comment by marlonbaeten** [comment]
Discussed with @lkleuver 

We introduce a vanilla translate function for now. We leverage a typescript interface to check at transpile time that all translations keys exist and are translated for the set of locales.

We only introduce dependencies (like i18-next) when we encounter necessary features that are not trivial to implement.

**Comment by praseodym** [comment]
Not sure what that will look like, but from a developer point of view I like how [Django's translation functionality](https://docs.djangoproject.com/en/5.1/topics/i18n/translation/) works. It would be nice if we could make it work similar to that.
