### ISSUE TITLE
Epic: User testing 25 oktober

### ISSUE THREAD

**Issue by jschuurk-kr** [kiesraad/abacus#498]
Epic is klaar als alle issues of opgelost zijn, of in een nieuwe epic zijn opgenomen, of geaccepteerd zijn.

- [x] Gebruikerstest uitvoeren: https://github.com/kiesraad/abacus-internal/issues/131
- [x] Bevindingen vastleggen: https://github.com/kiesraad/abacus-internal/issues/252

### Nog in overweging
- [ ] #600
- [ ] #599
- [x] Besluit: maybe later. Nu laten zoals het is ~**'Invoer afbreken' hernoemen naar 'Invoer onderbreken'**. Afweging: dit zou tot het omgekeerde effect kunnen leiden dat mensen die hun invoer willen weggooien, niet weten waar ze terecht moeten. (Hoewel die ook via de hoofdnavigatie weg kunnen navigeren, en dan de optie krijgen hun invoer niet te bewaren)~
- [ ] #598
- [ ] #597
- [ ] #596

### To do
Zie sub-issues

**Comment by jorisleker** [comment]
> [@jorisleker](https://github.com/jorisleker) _"Review teksten van alle foutmeldingen en waarschuwingen. Doel: maak ze korter, begrijpelijker en beter scanbaar."_ Ik zat me af te vragen of de foutmelding(en) en de acties van plek gewisseld moeten worden. Dat we eerst zeggen wat je moet doen (controleren en dan herstellen of de coördinator erbij halen) en daarna voor welke velden precies (bijv. velden A-D).

Ik ben bang dat alle foutmeldingen en waarschuwingen dan op elkaar gaan lijken. En dan worden ze nog minder gelezen :-). Het issue zit denk ik vooral in zinnen als de twee in onderstaand voorbeeld:

> **Controleer J (stembiljetten minder geteld) (F.303)**
> Je hebt bij Aantal kiezers en stemmers ingevuld dat er minder stemmen dan kiezers waren. Het aantal dat je bij J hebt ingevuld is niet gelijk aan het aantal minder getelde stembiljetten.
> Check of je het papieren proces-verbaal goed hebt overgenomen.

Veel te veel uitleg, en eigenlijk niet relevant voor iemand die alleen maar de taak heeft het papier over te nemen. We leggen veel te veel uit _waarom_ iets fout is, in plaats van dat we uitleggen _waar_ de fout allemaal kan zitten.

**Comment by jschuurk-kr** [comment]
@jorisleker Zonet hadden @Lionqueen94 en ik het over de foutmeldingen en waarschuwingen en misschien willen we iets anders laten zien aan invoerders en coördinatoren? Invoerders moeten vooral verteld worden dat ze met het papier moeten controleren. Coördinatoren moeten ook weten waarom Abacus bepaalde invoer opmerkelijk vindt.
