### ISSUE TITLE
Expand apportionment tests and add Kieswet article numbers to the code

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#736]
Also add Kieswet article numbers to the code

Tests for edge cases, see https://github.com/kiesraad/abacus/issues/545#issuecomment-2483221354

Testscenario’s from wettelijke toets 2022 (https://www.kiesraad.nl/adviezen-en-publicaties/rapporten/2022/1/31/toetsingsrapport-osv2020-u) need to be done for both < 19 and ≥ 19 seats:
| Nr. | Scenario | Omschrijving |
| -----|--------------|---------------------|
| GR1 | Zonder restzetels | Test om de basisfunctionaliteit van de software te analyseren zonder extra distributie van restzetels |
| GR2 | Met restzetels | Test om de basisfunctionaliteit te analyseren, vergelijkbaar met GR1, maar de verdeling van restzetels is vereist |
| GR3 | Restzetel naar partij zonder zetels bij directe toedeling | Test waarbij een partij geen zetels heeft na de eerste verdeling maar er een krijgt na een loterij |
| GR4 | Volstrekte meerderheid | Test waarbij een partij de absolute meerderheid heeft |
| GR5 | Volstrekte meerderheid na restzetels | Test waarbij een partij de absolute meerderheid heeft en de verdeling van de restzetel moet plaatsvinden |
| GR6 | Toewijzing restzetel na één loting | Test waarbij een loterij vereist is om de laatst overgebleven zetel toe te wijzen |
| GR7 | Toewijzing restzetels na meerdere lotingen | Test waarbij een loterij vereist is om meerdere zetels toe te wijzen |
| GR8 | Uitputting van lijsten | Test om uitputting van de lijst te testen |
| GR9 | Voorkeurstemmen | Test voor de toewijzing van zetels aan kandidaten met voldoende voorkeurstemmen |
| GR10 | Controle afronding voorkeursdrempel | Test om te controleren of de voorkeursdrempel niet is afgerond |
| GR11 | Gelijk aantal voorkeurstemmen binnen één partij | Test om een scenario te testen waarbij meerdere kandidaten binnen één partij hetzelfde aantal stemmen hebben, gevolgd door een loterij die de winnende kandidaat bepaalt |
| GR12 | Realistische test | Test met historische data in plaats van gegenereerde testdata |

Testcases need to be done for both < 19 and ≥ 19 seats:
- [x] Tests for 0 votes for all parties
- [x] GR1: Zonder restzetels - Test om de basisfunctionaliteit van de software te analyseren zonder extra distributie van restzetels
- [x] GR2: Met restzetels - Test om de basisfunctionaliteit te analyseren, vergelijkbaar met GR1, maar de verdeling van restzetels is vereist
- [ ] GR3: Restzetel naar partij zonder zetels bij directe toedeling - Test waarbij een partij geen zetels heeft na de eerste verdeling maar er een krijgt na een loterij #788
- [x] GR4: Volstrekte meerderheid - Test waarbij een partij de absolute meerderheid heeft
- [ ] GR5a: Volstrekte meerderheid na restzetels - Test waarbij een partij de absolute meerderheid heeft en de verdeling van de restzetel moet plaatsvinden zonder loting #785
- [ ] GR5b: Volstrekte meerderheid na restzetels - Test waarbij een partij de absolute meerderheid heeft en de verdeling van de restzetel moet plaatsvinden via loting #788
- [ ] GR6: Toewijzing restzetel na één loting - Test waarbij een loterij vereist is om de laatst overgebleven zetel toe te wijzen #788
- [ ] GR7: Toewijzing restzetels na meerdere lotingen - Test waarbij een loterij vereist is om meerdere zetels toe te wijzen #788
- [ ] GR8: Uitputting van lijsten - Test om uitputting van de lijst te testen #787
- [ ] GR9: Voorkeurstemmen - Test voor de toewijzing van zetels aan kandidaten met voldoende voorkeurstemmen #787
- [ ] GR10: Controle afronding voorkeursdrempel - Test om te controleren of de voorkeursdrempel niet is afgerond #787
- [ ] GR11: Gelijk aantal voorkeurstemmen binnen één partij - Test om een scenario te testen waarbij meerdere kandidaten binnen één partij hetzelfde aantal stemmen hebben, gevolgd door een loterij die de winnende kandidaat bepaalt #787
- [ ] GR12: Realistische test - Test met historische data in plaats van gegenereerde testdata #787

Testcases live on the G-drive:
- `G:\CS\KIESRAAD\Team D&T\OSV2020\VAPP-U\Test data VAPP\GR\E2E Algoritme en Functionele test - v1.5.0`
- `G:\CS\KIESRAAD\Team D&T\OSV2020\VAPP-U\Test data VAPP van IVU\VAPP-U-OSV-testcases\GRTestCasesAndResults.xls` (expansive testcases for < 19 seats)
- `G:\CS\KIESRAAD\Team D&T\OSV2020\VAPP-U\Test data VAPP van IVU\VAPP-U-OSV-testcases\GR2PSTestCasesAndResults.xls` (expansive testcases for ≥ 19 seats)

**Comment by Lionqueen94** [comment]
Added all not yet implemented testcases to their respective issues/epics and linked those issues/epics in the description.
